# DON'T EDIT THIS!
#
# Codecrafters relies on this file being intact to run tests successfully. Any changes
# here will not reflect when CodeCrafters tests your code, and might even cause build
# failures.
#
# DON'T EDIT THIS!

name:                hs-redis-clone
version:             0.1.0.0
license:             BSD3

dependencies:
- base >= 4.7 && < 5
- network-simple  # establish a simple TCP network
- bytestring  # useful to send bytes over the network
- network  # required when using bytestring
- megaparsec  # may be useful for parsing the input
- parser-combinators  # contains a helpful count function
- attoparsec # alternative to megaparsec and parser-combinators
- text  # use Text rather than String
- stm  # may help with a concurrent database
- containers  # may help with the database structure and debugging
- time  # may help with the expiry function

executables:
  hs-redis-clone-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
